"""
Constants for the objects in the Screen
"""
REC_TO_ARROW_GAP = 30
SQUARE_DEFAULT_LEN = 20
SQUARE_SIZE = 100

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 900


REC_SQ_PADDING = 20
GAP = 20 + REC_SQ_PADDING
RECTANGLE_WID = SQUARE_SIZE + GAP
RECTANGLE_LEN = SQUARE_SIZE * 3 + GAP * 3


MOVE = RECTANGLE_WID
